name: test_apex_charts
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: eugene.kot <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  js: ^0.6.0

dev_dependencies:
  build_runner: ^0.10.2
  build_web_compilers: ^0.4.0
